import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main
          style={{
            margin: "100px",
            padding: "5px",
            borderBottom: "1px solid #eee",
          }}
        >
          <div>
            <Link href="/">
              <h2 style={{ textDecoration: "underline", color: "#6ea9d7" }}>
                Find your Pokemon
              </h2>
            </Link>
          </div>
        </main>
        {children}
      </body>
    </html>
  );
}
